### ISSUE TITLE
BayesPLDA

### ISSUE THREAD

**Issue by ZhouWenjun2019** [enmwmak/ML-for-Spkrec#1]
I couldn't find BayesPLDA in MATLAB program of SD-mPLDA, is it missed?

**Comment by enmwmak** [comment]
Dear Zhou,

I think you are talking about comp_mGPLDA.m

You may put all of the .m files under your BayesPLDA/ directory. But does not have to call "BayesPLDA". It is the name of my directory. That's why I have the code

if (strcmp(computer,'PCWIN')==1 || strcmp(computer,'PCWIN64')==1),
    addpath 'D:/so/Matlab/PLDA/BayesPLDA';
else
    addpath '~/so/Matlab/PLDA/BayesPLDA';
end

This code fragment enables you to run comp_mGPLDA.m outside the BayesPLDA/ directory. But the fragment is not necessary if you run within the directory containing all the .m files.

MW


Man Wai MAK

Professor

Dept. of Electronic and Information Engineering

The Hong Kong Polytechnic University

http://www.eie.polyu.edu.hk/~mwmak/

________________________________

**Comment by ZhouWenjun2019** [comment]
Thank you, professor.
